/**
 * ICS4UR Computer Science, 12 
 * Brampton, Canada
 *
 * https://github.com/HarisK03/
 * https://repl.it/@HarisKamal
 *
 * modified     20201014
 * date         20201013
 * @filename	EmployeeRecords.java
 * @author      hkamal
 * @version     1.0
 * @see         EmployeeRecords program Assignment 2.6 - manage Employees within a company
 */

import java.util.*;
import javax.swing.JOptionPane;

public class EmployeeRecords extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeRecords
     */
    public EmployeeRecords() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblFirstN = new javax.swing.JLabel();
        lblAS = new javax.swing.JLabel();
        lblLastN = new javax.swing.JLabel();
        lblSD = new javax.swing.JLabel();
        inputLastN = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        display = new javax.swing.JTextArea();
        inputAS = new javax.swing.JTextField();
        inputSD = new javax.swing.JTextField();
        inputID = new javax.swing.JTextField();
        inputFirstN = new javax.swing.JTextField();
        lblAS1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Open Sans", 1, 36)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Employee Records");

        lblID.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        lblID.setText("ID#");

        lblFirstN.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        lblFirstN.setText("First Name");

        lblAS.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        lblAS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAS.setText("Annual Salary");

        lblLastN.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        lblLastN.setText("Last Name");

        lblSD.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        lblSD.setText("Start Date");

        inputLastN.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        btnAdd.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRemove.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        display.setEditable(false);
        display.setColumns(20);
        display.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        display.setRows(5);
        jScrollPane1.setViewportView(display);

        inputAS.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        inputSD.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        inputID.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        inputFirstN.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        lblAS1.setFont(new java.awt.Font("Open Sans", 1, 10)); // NOI18N
        lblAS1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAS1.setText("Format: Name | ID | Annual Salary | Start Date");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAS1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(inputFirstN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(inputLastN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(lblFirstN)
                                .addGap(71, 71, 71)
                                .addComponent(lblLastN))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(lblID)))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputAS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSD)
                                .addGap(16, 16, 16))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(inputSD, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAdd)
                .addGap(31, 31, 31)
                .addComponent(btnRemove)
                .addGap(32, 32, 32)
                .addComponent(btnExit)
                .addGap(128, 128, 128))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastN)
                    .addComponent(lblFirstN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputLastN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputFirstN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputSD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblAS)
                            .addGap(32, 32, 32))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblID)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(inputAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(inputID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnRemove)
                    .addComponent(btnExit))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAS1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    ArrayList <Employee> emp = new ArrayList <Employee>();
    int a = 0;
    
    // add new employee to the company
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            Employee e;
            String eName = inputFirstN.getText() + " " + inputLastN.getText();
            int id = Integer.parseInt(inputID.getText());
            double as = Double.parseDouble(inputAS.getText());
            String sd = inputSD.getText();
            for (int x = 0; x < emp.size(); x++) {
                if (emp.get(x).id == Integer.parseInt(inputID.getText())) {
                    JOptionPane.showMessageDialog(null, "Two employees can't have the same ID!");
                    return;
                }
            }
            if (inputFirstN.getText().isEmpty() || inputLastN.getText().isEmpty() || inputID.getText().isEmpty() || inputAS.getText().isEmpty() || inputSD.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "One or more values are empty!");
                return;
            }
            else if (id < 0) {
                JOptionPane.showMessageDialog(null, "Our company does not have negative ID's!");
                return;
            } 
            else if (as < 0) {
                JOptionPane.showMessageDialog(null, "Salary can not be negative!");
                return;
            }    
            else {
                e = new Employee(eName, id, as, sd);
                emp.add(e);
            }
            a++;
            display.append((emp.get(a-1).eName) + " | " + (emp.get(a-1).id) + " | " + (emp.get(a-1).as) + " | " + (emp.get(a-1).sd) + "\n");
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ensure ID is an integer and salary is a number!");
        }
    }//GEN-LAST:event_btnAddActionPerformed
    
    // remove an employee from the company
    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        for (int i = 0; i < emp.size(); i++) {
            if (emp.get(i).id == Integer.parseInt(inputID.getText())) {
                emp.remove(i);
                a--;
                display.setText("");
                for (int j = 0; j < emp.size(); j++) {
                    display.append(emp.get(j).eName + " | " + emp.get(j).id + " | " + emp.get(j).as + " | " + emp.get(j).sd + "\n");
                }
                return;
            } 
        }
        JOptionPane.showMessageDialog(null, "No employee with that ID works here!");
        return;
    }//GEN-LAST:event_btnRemoveActionPerformed

    // exit
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed
    
    // new Employee class to assign vars
    class Employee {
        String eName, sd;
        int id;
        double as;
        Employee (String ceName, int cId, double cAs, String cSd) {
            eName = ceName;
            id = cId;
            as = cAs;
            sd = cSd;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeRecords().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnRemove;
    private javax.swing.JTextArea display;
    private javax.swing.JTextField inputAS;
    private javax.swing.JTextField inputFirstN;
    private javax.swing.JTextField inputID;
    private javax.swing.JTextField inputLastN;
    private javax.swing.JTextField inputSD;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAS;
    private javax.swing.JLabel lblAS1;
    private javax.swing.JLabel lblFirstN;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblLastN;
    private javax.swing.JLabel lblSD;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
