/**
 * ICS4UR Computer Science, 12 
 * Brampton, Canada
 *
 * https://github.com/HarisK03/
 * https://repl.it/@HarisKamal
 *
 * modified     20201009
 * date         20200928
 * @filename	MathMethods.java
 * @author      hkamal
 * @version     1.1
 * @see         MathMethods program assignment 1.6 - various methods from the Math class
 */

import javax.swing.JOptionPane;

public class MathMethods extends javax.swing.JFrame {
    
    /**
     * Creates new form MathMethods
     */
    public MathMethods() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAbs = new javax.swing.JLabel();
        btnAbs = new javax.swing.JButton();
        inputAbs = new javax.swing.JTextField();
        outputAbs = new javax.swing.JTextField();
        lblSqrt = new javax.swing.JLabel();
        lblCbrt = new javax.swing.JLabel();
        lblPower = new javax.swing.JLabel();
        lblRandom = new javax.swing.JLabel();
        lblAbsI = new javax.swing.JLabel();
        lblAbsO = new javax.swing.JLabel();
        btnSqrt = new javax.swing.JButton();
        inputSqrt = new javax.swing.JTextField();
        outputSqrt = new javax.swing.JTextField();
        lblSqrtI = new javax.swing.JLabel();
        lblSqrtO = new javax.swing.JLabel();
        btnCbrt = new javax.swing.JButton();
        lblCbrtO = new javax.swing.JLabel();
        lblCbrtI = new javax.swing.JLabel();
        inputCbrt = new javax.swing.JTextField();
        outputCbrt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnPower = new javax.swing.JButton();
        lblPowerO = new javax.swing.JLabel();
        lblBaseI = new javax.swing.JLabel();
        inputBase = new javax.swing.JTextField();
        outputPower = new javax.swing.JTextField();
        lblExponentI = new javax.swing.JLabel();
        inputExponent = new javax.swing.JTextField();
        btnRandom = new javax.swing.JButton();
        outputRandom = new javax.swing.JTextField();
        btnRound = new javax.swing.JButton();
        lblRoundO = new javax.swing.JLabel();
        lblRoundI = new javax.swing.JLabel();
        inputRound = new javax.swing.JTextField();
        lblRound = new javax.swing.JLabel();
        outputRound = new javax.swing.JTextField();
        lblRandomO = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnDouble = new javax.swing.JButton();
        lblDoubleI = new javax.swing.JLabel();
        lblDoubleO = new javax.swing.JLabel();
        outputDouble = new javax.swing.JTextField();
        inputDouble = new javax.swing.JTextField();
        lblDouble = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblAbs.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAbs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAbs.setText("Absolute Value");

        btnAbs.setText("Calculate");
        btnAbs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbsActionPerformed(evt);
            }
        });

        inputAbs.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputAbs.setToolTipText("");
        inputAbs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAbsActionPerformed(evt);
            }
        });

        outputAbs.setEditable(false);
        outputAbs.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        outputAbs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputAbsActionPerformed(evt);
            }
        });

        lblSqrt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSqrt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSqrt.setText("Square Root");

        lblCbrt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCbrt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCbrt.setText("Cube Root");

        lblPower.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPower.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPower.setText("Power");

        lblRandom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRandom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRandom.setText("Random");

        lblAbsI.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblAbsI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAbsI.setText("Input");

        lblAbsO.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblAbsO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAbsO.setText("Ouput");

        btnSqrt.setText("Calculate");
        btnSqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSqrtActionPerformed(evt);
            }
        });

        inputSqrt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputSqrt.setToolTipText("");
        inputSqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSqrtActionPerformed(evt);
            }
        });

        outputSqrt.setEditable(false);
        outputSqrt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        outputSqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputSqrtActionPerformed(evt);
            }
        });

        lblSqrtI.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblSqrtI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSqrtI.setText("Input");

        lblSqrtO.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblSqrtO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSqrtO.setText("Ouput");

        btnCbrt.setText("Calculate");
        btnCbrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCbrtActionPerformed(evt);
            }
        });

        lblCbrtO.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblCbrtO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCbrtO.setText("Ouput");

        lblCbrtI.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblCbrtI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCbrtI.setText("Input");

        inputCbrt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputCbrt.setToolTipText("");
        inputCbrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCbrtActionPerformed(evt);
            }
        });

        outputCbrt.setEditable(false);
        outputCbrt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        outputCbrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputCbrtActionPerformed(evt);
            }
        });

        btnPower.setText("Calculate");
        btnPower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPowerActionPerformed(evt);
            }
        });

        lblPowerO.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblPowerO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPowerO.setText("Ouput");

        lblBaseI.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblBaseI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBaseI.setText("Base");

        inputBase.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputBase.setToolTipText("");
        inputBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBaseActionPerformed(evt);
            }
        });

        outputPower.setEditable(false);
        outputPower.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        outputPower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputPowerActionPerformed(evt);
            }
        });

        lblExponentI.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblExponentI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExponentI.setText("Exponent");

        inputExponent.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputExponent.setToolTipText("");
        inputExponent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputExponentActionPerformed(evt);
            }
        });

        btnRandom.setText("Calculate");
        btnRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRandomActionPerformed(evt);
            }
        });

        outputRandom.setEditable(false);
        outputRandom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        outputRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputRandomActionPerformed(evt);
            }
        });

        btnRound.setText("Calculate");
        btnRound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoundActionPerformed(evt);
            }
        });

        lblRoundO.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblRoundO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRoundO.setText("Ouput");

        lblRoundI.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblRoundI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRoundI.setText("Input");

        inputRound.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputRound.setToolTipText("");
        inputRound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputRoundActionPerformed(evt);
            }
        });

        lblRound.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRound.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRound.setText("Round");

        outputRound.setEditable(false);
        outputRound.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        outputRound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputRoundActionPerformed(evt);
            }
        });

        lblRandomO.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblRandomO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRandomO.setText("Ouput");

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("MathMethods");

        btnExit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnDouble.setText("Calculate");
        btnDouble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoubleActionPerformed(evt);
            }
        });

        lblDoubleI.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblDoubleI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDoubleI.setText("Input");

        lblDoubleO.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblDoubleO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDoubleO.setText("Ouput");

        outputDouble.setEditable(false);
        outputDouble.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        outputDouble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputDoubleActionPerformed(evt);
            }
        });

        inputDouble.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputDouble.setToolTipText("");
        inputDouble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDoubleActionPerformed(evt);
            }
        });

        lblDouble.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDouble.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDouble.setText("Double");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(inputAbs, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(outputAbs, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAbsI, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAbsO, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(inputSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(outputSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSqrtI, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSqrtO, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(158, 158, 158))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnPower, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblPower, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(inputBase, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblBaseI, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(inputExponent, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblExponentI, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(29, 29, 29)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(outputPower, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblPowerO, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblRandom, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnRandom, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblDouble, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(inputDouble, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(outputDouble, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblDoubleI, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblDoubleO, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(btnDouble, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(77, 77, 77))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(102, 102, 102)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblRandomO, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(outputRandom, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRound, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(inputRound, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(outputRound, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblRoundI, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblRoundO, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnRound, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblAbs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAbs, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 257, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(inputCbrt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(outputCbrt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCbrtI, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblCbrtO, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnCbrt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCbrt, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(29, 29, 29))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAbs, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCbrt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputAbs, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(outputAbs, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAbsI)
                            .addComponent(lblAbsO))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAbs, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(outputSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSqrtI)
                            .addComponent(lblSqrtO)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(btnCbrt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputCbrt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(outputCbrt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCbrtI)
                            .addComponent(lblCbrtO))))
                .addGap(27, 27, 27)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRound, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputRound, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(outputRound, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRoundI)
                            .addComponent(lblRoundO))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRound, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRandom, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPower, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(inputBase, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblBaseI)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(outputPower, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(inputExponent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(outputRandom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblExponentI)
                                            .addComponent(lblRandomO, javax.swing.GroupLayout.Alignment.TRAILING)))))
                            .addComponent(lblRandom, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(lblPowerO)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPower, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDouble, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputDouble, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outputDouble, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDoubleI)
                    .addComponent(lblDoubleO))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDouble, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int count = 0;
    
    private void inputAbsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAbsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputAbsActionPerformed

    private void outputAbsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputAbsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputAbsActionPerformed

    private void btnAbsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbsActionPerformed
        // uses .abs() method in Math class and displays absolute value of input
        try {
            double inputAbsVal = Double.parseDouble(inputAbs.getText());
            outputAbs.setText(Double.toString(Math.round((Math.abs(inputAbsVal))*100)/100.0));
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ensure all inputs are numeric!");
        }
    }//GEN-LAST:event_btnAbsActionPerformed

    private void btnSqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSqrtActionPerformed
        // uses .sqrt() method in Math class and displays square root of input
        try {
            double inputSqrtVal = Double.parseDouble(inputSqrt.getText());
            // no real roots for negative sqrt
            if (inputSqrtVal < 0) {
                JOptionPane.showMessageDialog(null, "Can't square a negative!");
                return;
            }
            outputSqrt.setText(Double.toString(Math.round((Math.sqrt(inputSqrtVal))*100)/100.0));
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ensure all inputs are numeric!");
        }
    }//GEN-LAST:event_btnSqrtActionPerformed

    private void inputSqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSqrtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSqrtActionPerformed

    private void outputSqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputSqrtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputSqrtActionPerformed

    private void btnCbrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCbrtActionPerformed
        // uses .cbrt() method in Math class and displays cube root of input
        try {
            double inputCbrtVal = Double.parseDouble(inputCbrt.getText());
            outputCbrt.setText(Double.toString(Math.round((Math.cbrt(inputCbrtVal))*100)/100.0));
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ensure all inputs are numeric!");
        }
    }//GEN-LAST:event_btnCbrtActionPerformed

    private void inputCbrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCbrtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCbrtActionPerformed

    private void outputCbrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputCbrtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputCbrtActionPerformed

    private void btnPowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPowerActionPerformed
        // uses .pow() method in Math class and displays base to the power of exponent
        try {
            double base = Double.parseDouble(inputBase.getText());
            int exponent = Integer.parseInt(inputExponent.getText());
            outputPower.setText(Double.toString(Math.round((Math.pow(base, exponent))*100)/100.0));    
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ensure all inputs are numeric!");
        }
    }//GEN-LAST:event_btnPowerActionPerformed

    private void inputBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputBaseActionPerformed

    private void outputPowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputPowerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputPowerActionPerformed

    private void inputExponentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputExponentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputExponentActionPerformed

    private void btnRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRandomActionPerformed
        // uses .random() method in Math class and displays a random number between 1 and 100
        try {
            outputRandom.setText(Double.toString((Math.round((Math.random())*100)/100.0)*100));
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ensure all inputs are numeric!");
        }
    }//GEN-LAST:event_btnRandomActionPerformed

    private void outputRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputRandomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputRandomActionPerformed

    private void btnRoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoundActionPerformed
        // uses .round() method in Math class and rounded input
        try {
            double inputRoundVal = Double.parseDouble(inputRound.getText());
            outputRound.setText(Double.toString(Math.round(inputRoundVal)));
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ensure all inputs are numeric!");
        }
    }//GEN-LAST:event_btnRoundActionPerformed

    private void inputRoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputRoundActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputRoundActionPerformed

    private void outputRoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputRoundActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputRoundActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // call custom method
        popupExit();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnDoubleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoubleActionPerformed
        // custom function that uses doubleReturn() method to return twice the input and display as output
        try {
            double inputDoubleVal = doubleReturn(Double.parseDouble(inputDouble.getText()));
            outputDouble.setText(Double.toString((Math.round((inputDoubleVal)*100))/100.0));
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ensure all inputs are numeric!");
        }
    }//GEN-LAST:event_btnDoubleActionPerformed

    public static double doubleReturn(double inputDoubleVal) {
        // retrieves input and returns x2
        return inputDoubleVal*2;
    }
    
    private void outputDoubleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputDoubleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputDoubleActionPerformed

    private void inputDoubleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDoubleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDoubleActionPerformed
    
    public void popupExit() {        
        // open a JOptionPane and exit if count > 1
        if (count == 0) {
            JOptionPane.showMessageDialog(null, "Leaving without saying hi?");
            count++;
            return;
        }
        else {
            JOptionPane.showMessageDialog(null, "Bye!");
            System.exit(0);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MathMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MathMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MathMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MathMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MathMethods().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbs;
    private javax.swing.JButton btnCbrt;
    private javax.swing.JButton btnDouble;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPower;
    private javax.swing.JButton btnRandom;
    private javax.swing.JButton btnRound;
    private javax.swing.JButton btnSqrt;
    private javax.swing.JTextField inputAbs;
    private javax.swing.JTextField inputBase;
    private javax.swing.JTextField inputCbrt;
    private javax.swing.JTextField inputDouble;
    private javax.swing.JTextField inputExponent;
    private javax.swing.JTextField inputRound;
    private javax.swing.JTextField inputSqrt;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblAbs;
    private javax.swing.JLabel lblAbsI;
    private javax.swing.JLabel lblAbsO;
    private javax.swing.JLabel lblBaseI;
    private javax.swing.JLabel lblCbrt;
    private javax.swing.JLabel lblCbrtI;
    private javax.swing.JLabel lblCbrtO;
    private javax.swing.JLabel lblDouble;
    private javax.swing.JLabel lblDoubleI;
    private javax.swing.JLabel lblDoubleO;
    private javax.swing.JLabel lblExponentI;
    private javax.swing.JLabel lblPower;
    private javax.swing.JLabel lblPowerO;
    private javax.swing.JLabel lblRandom;
    private javax.swing.JLabel lblRandomO;
    private javax.swing.JLabel lblRound;
    private javax.swing.JLabel lblRoundI;
    private javax.swing.JLabel lblRoundO;
    private javax.swing.JLabel lblSqrt;
    private javax.swing.JLabel lblSqrtI;
    private javax.swing.JLabel lblSqrtO;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField outputAbs;
    private javax.swing.JTextField outputCbrt;
    private javax.swing.JTextField outputDouble;
    private javax.swing.JTextField outputPower;
    private javax.swing.JTextField outputRandom;
    private javax.swing.JTextField outputRound;
    private javax.swing.JTextField outputSqrt;
    // End of variables declaration//GEN-END:variables
}
