/**
 * ICS4UR Computer Science, 12 
 * Brampton, Canada
 *
 * https://github.com/HarisK03/
 * https://repl.it/@HarisKamal
 *
 * modified     20201009
 * date         20200924
 * @filename	SleepCalculator.java
 * @author      hkamal
 * @version     1.1
 * @see         SleepCalculator program assignment 1.4 - calculate days alive and sleep between two dates
 */
        
public class SleepCalculator extends javax.swing.JFrame {
    
    /**
     * Creates new form SleepCalculator
     */
    public SleepCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        BdEnter1 = new javax.swing.JLabel();
        SleepCalculatorTitle = new javax.swing.JLabel();
        lblBdDay = new javax.swing.JLabel();
        lblBdMonth = new javax.swing.JLabel();
        BdEnter = new javax.swing.JLabel();
        TdEnter = new javax.swing.JLabel();
        calcButton = new javax.swing.JButton();
        bdDay = new javax.swing.JTextField();
        bdMonth = new javax.swing.JTextField();
        bdYear = new javax.swing.JTextField();
        tdDay = new javax.swing.JTextField();
        lblTdDay = new javax.swing.JLabel();
        lblTdMonth = new javax.swing.JLabel();
        lblTdYear = new javax.swing.JLabel();
        tdMonth = new javax.swing.JTextField();
        tdYear = new javax.swing.JTextField();
        exitButton = new javax.swing.JButton();
        aliveTime = new javax.swing.JTextField();
        sleepTime = new javax.swing.JTextField();
        lblBdYear = new javax.swing.JLabel();
        BdEnter2 = new javax.swing.JLabel();
        BdEnter3 = new javax.swing.JLabel();

        jTextField2.setText("jTextField1");

        jTextField4.setText("jTextField1");

        jTextField6.setText("jTextField1");

        jTextField7.setText("jTextField1");

        jTextField8.setText("jTextField1");

        jLabel5.setText("Year");

        jLabel6.setText("Month");

        jLabel7.setText("Day");

        jButton3.setText("Calculate");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        BdEnter1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BdEnter1.setText("Enter Your Birthdate");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SleepCalculatorTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        SleepCalculatorTitle.setForeground(new java.awt.Color(0, 0, 255));
        SleepCalculatorTitle.setText("Sleep Calculator");

        lblBdDay.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblBdDay.setText("Day");

        lblBdMonth.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblBdMonth.setText("Month");

        BdEnter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BdEnter.setText("Enter Your Birthdate");

        TdEnter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TdEnter.setText("Enter Today's Date");

        calcButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        calcButton.setText("Calculate");
        calcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonActionPerformed(evt);
            }
        });

        lblTdDay.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTdDay.setText("Day");

        lblTdMonth.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTdMonth.setText("Month");

        lblTdYear.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTdYear.setText("Year");

        tdYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdYearActionPerformed(evt);
            }
        });

        exitButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        aliveTime.setEditable(false);
        aliveTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aliveTimeActionPerformed(evt);
            }
        });

        sleepTime.setEditable(false);
        sleepTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sleepTimeActionPerformed(evt);
            }
        });

        lblBdYear.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblBdYear.setText("Year");

        BdEnter2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BdEnter2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BdEnter2.setText("Lifespan");

        BdEnter3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BdEnter3.setText("Sleep Duration");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(SleepCalculatorTitle)
                .addContainerGap(102, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblBdYear)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bdYear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblBdMonth)
                                        .addComponent(lblBdDay))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(bdDay, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bdMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(BdEnter))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTdDay)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tdDay, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(lblTdMonth)
                                            .addGap(18, 18, 18))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblTdYear)
                                            .addGap(26, 26, 26)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tdYear)
                                        .addComponent(tdMonth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(TdEnter)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BdEnter3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BdEnter2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sleepTime, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aliveTime, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)))
                .addGap(57, 57, 57))
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(calcButton)
                .addGap(39, 39, 39)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SleepCalculatorTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TdEnter)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTdDay)
                            .addComponent(tdDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTdMonth)
                            .addComponent(tdMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTdYear)
                            .addComponent(tdYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BdEnter)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBdDay)
                            .addComponent(bdDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBdMonth)
                            .addComponent(bdMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBdYear)
                            .addComponent(bdYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitButton)
                    .addComponent(calcButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aliveTime, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BdEnter2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sleepTime, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BdEnter3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcButtonActionPerformed
        try {
            // declare variables for jtextfields and get int inputs
            int bdDayDate = Integer.parseInt(bdDay.getText());
            int bdMonthDate = Integer.parseInt(bdMonth.getText());
            int bdYearDate = Integer.parseInt(bdYear.getText());
            int tdDayDate = Integer.parseInt(tdDay.getText());
            int tdMonthDate = Integer.parseInt(tdMonth.getText());
            int tdYearDate = Integer.parseInt(tdYear.getText());
            
            // calculate difference between today's date and user birth date
            int yearDiff = tdYearDate - bdYearDate;
            int monthDiff = tdMonthDate - bdMonthDate;
            int dayDiff = tdDayDate - bdDayDate;
            
            // convert to days and hours
            int alive = (yearDiff*365) + (monthDiff*30) + dayDiff;
            int slept = (alive*8); 
            
            // output if alive or sleep < 0 exception
            if (alive < 0) {
                aliveTime.setText("Hmm...");
                sleepTime.setText("Are you a time traveller!?"); 
            }
            
            // ensure inputs dont exceed allowed field range
            else if (bdDayDate < 0 || bdDayDate > 30 || bdMonthDate < 0 || bdMonthDate > 12 || bdYearDate < 0 || tdDayDate < 0 || tdDayDate > 30 || tdMonthDate < 0 || tdMonthDate > 12 || tdYearDate < 0 ) {
                aliveTime.setText("Never seen that input before...");
                sleepTime.setText("Fix the invalid input!"); 
            }
            
            // output alive and sleep time if vars > 0
            else {
                aliveTime.setText("You have been alive for " + Integer.toString(alive) + " days");
                sleepTime.setText("You have slept for " + Integer.toString(slept) + " hours");
            }
        }
        
        // handle exception if input != int
        catch (Exception e) {
            aliveTime.setText("Are you alive?");
            sleepTime.setText("*Yawn* Looking for valid input...");
        }
    }//GEN-LAST:event_calcButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void sleepTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sleepTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sleepTimeActionPerformed

    private void tdYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tdYearActionPerformed

    private void aliveTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aliveTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aliveTimeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SleepCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SleepCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SleepCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SleepCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SleepCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BdEnter;
    private javax.swing.JLabel BdEnter1;
    private javax.swing.JLabel BdEnter2;
    private javax.swing.JLabel BdEnter3;
    private javax.swing.JLabel SleepCalculatorTitle;
    private javax.swing.JLabel TdEnter;
    private javax.swing.JTextField aliveTime;
    private javax.swing.JTextField bdDay;
    private javax.swing.JTextField bdMonth;
    private javax.swing.JTextField bdYear;
    private javax.swing.JButton calcButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel lblBdDay;
    private javax.swing.JLabel lblBdMonth;
    private javax.swing.JLabel lblBdYear;
    private javax.swing.JLabel lblTdDay;
    private javax.swing.JLabel lblTdMonth;
    private javax.swing.JLabel lblTdYear;
    private javax.swing.JTextField sleepTime;
    private javax.swing.JTextField tdDay;
    private javax.swing.JTextField tdMonth;
    private javax.swing.JTextField tdYear;
    // End of variables declaration//GEN-END:variables
}
