/**
 * ICS4UR Computer Science, 12 
 * Brampton, Canada
 *
 * https://github.com/HarisK03/
 * https://repl.it/@HarisKamal
 *
 * modified     20201012
 * date         20201008
 * @filename	StudentGrades.java
 * @author      hkamal
 * @version     1.0
 * @see         StudentGrades program Assignment 2.4 - add 4 marks for up to 15 students and retrieve course/student average
 */

import java.util.Arrays;
import javax.swing.JOptionPane;

public class StudentGrades extends javax.swing.JFrame {
    
    int a = 0;
    String [][] sData = new String [15][5];

    /**
     * Creates new form StudentGrades
     */
    public StudentGrades() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputTest2 = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        lblFirstN = new javax.swing.JLabel();
        lblLastN = new javax.swing.JLabel();
        lblTest1 = new javax.swing.JLabel();
        lblTest2 = new javax.swing.JLabel();
        lblTest3 = new javax.swing.JLabel();
        lblTest4 = new javax.swing.JLabel();
        inputLastN = new javax.swing.JTextField();
        inputTest1 = new javax.swing.JTextField();
        inputTest4 = new javax.swing.JTextField();
        inputTest3 = new javax.swing.JTextField();
        btnCA = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnSA = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        display = new javax.swing.JTextArea();
        inputFirstN = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        inputTest2.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        lblTitle.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("StudentGrades");

        lblFirstN.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        lblFirstN.setText("First Name");

        lblLastN.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        lblLastN.setText("Last Name");

        lblTest1.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        lblTest1.setText("Test 1");

        lblTest2.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        lblTest2.setText("Test 2");

        lblTest3.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        lblTest3.setText("Test 3");

        lblTest4.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        lblTest4.setText("Test 4");

        inputLastN.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        inputTest1.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        inputTest4.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        inputTest3.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        btnCA.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        btnCA.setText("Course Average");
        btnCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCAActionPerformed(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnSA.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        btnSA.setText("Student Average");
        btnSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSAActionPerformed(evt);
            }
        });

        display.setEditable(false);
        display.setColumns(20);
        display.setRows(5);
        jScrollPane1.setViewportView(display);

        inputFirstN.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(inputFirstN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(inputLastN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnSA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(79, 79, 79))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(lblFirstN)
                        .addGap(94, 94, 94)
                        .addComponent(lblLastN))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(73, 73, 73)
                            .addComponent(lblTest1)
                            .addGap(61, 61, 61)
                            .addComponent(lblTest2)
                            .addGap(62, 62, 62)
                            .addComponent(lblTest3)
                            .addGap(62, 62, 62)
                            .addComponent(lblTest4)
                            .addGap(23, 23, 23))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(51, 51, 51)
                            .addComponent(inputTest1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(inputTest2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(inputTest3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(inputTest4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstN)
                    .addComponent(lblLastN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputLastN, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputFirstN, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTest2)
                    .addComponent(lblTest1)
                    .addComponent(lblTest3)
                    .addComponent(lblTest4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputTest1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputTest2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputTest3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputTest4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(btnSA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit)
                    .addComponent(btnCA)
                    .addComponent(btnAdd))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // collect all marks from all students and divide by amount of marks to get course average
    private void btnCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCAActionPerformed
        
            double sum = 0;
            double count = 0;
            for (int i = 0; i < sData.length; i++) {
                for (int j = 1; j < sData[i].length; j++) {
                    if (sData[i][j] != null) {
                        sum += Double.parseDouble(sData[i][j]);
                        count++;
                    }
                } 
            }
            display.setText("The course average is " + Double.toString(sum/count) + "%." + "\n");
            for (int k = 0; k < a; k++) {
                display.append(Arrays.deepToString(sData[k]) + "\n");
            }
    }//GEN-LAST:event_btnCAActionPerformed

    // add name and marks into the array
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            String sName = inputFirstN.getText() + " " + inputLastN.getText(); 
            sData[a][0] = sName;
            sData[a][1] = inputTest1.getText();
            sData[a][2] = inputTest2.getText();
            sData[a][3] = inputTest3.getText();
            sData[a][4] = inputTest4.getText();
            
            if (inputFirstN.getText().isEmpty() || inputLastN.getText().isEmpty() || sData[a][1].isEmpty() || sData[a][2].isEmpty() || sData[a][3].isEmpty() || sData[a][4].isEmpty()) {
                JOptionPane.showMessageDialog(null, "You have an empty value!");
            }
            else if (Double.parseDouble(sData[a][1]) > 100 || Double.parseDouble(sData[a][1]) < 0 || Double.parseDouble(sData[a][2]) > 100 || Double.parseDouble(sData[a][2]) < 0 || Double.parseDouble(sData[a][3]) > 100 || Double.parseDouble(sData[a][3]) < 0 || Double.parseDouble(sData[a][4]) > 100 || Double.parseDouble(sData[a][4]) < 0 || (inputFirstN.getText().isEmpty() && inputLastN.getText().isEmpty())) {
                JOptionPane.showMessageDialog(null, "Hmm those marks look fishy.");
            }
            else {
                a++;
                display.setText("");
                for (int i = 0; i < a; i++) {
                    display.append(Arrays.deepToString(sData[i]) + "\n");
                }
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Max students reached or invalid input!");
            String sName = null; 
            sData[a][0] = null;
            sData[a][1] = null;
            sData[a][2] = null;
            sData[a][3] = null;
            sData[a][4] = null;
        }
    }                                      
    
    // list all arrays
    private void listArr() {
        display.append(Arrays.deepToString(sData[a-1]) + "\n");
    }//GEN-LAST:event_btnAddActionPerformed

    // exit
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    // get student average
    private void btnSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSAActionPerformed
        try {
            String sName = inputFirstN.getText() + " " + inputLastN.getText();
            if (sName.isEmpty()) {
                JOptionPane.showMessageDialog(null, "You have an empty value!");
            }
            else {
                for (int i = 0; i < sData.length; i++) {
                    // skip null
                    if (sData[i][0] == null) {}
                    else if (sData[i][0].equals(sName)) {
                        double sAvrg = ((Double.parseDouble(sData[i][1]) + Double.parseDouble(sData[i][2]) + Double.parseDouble(sData[i][3]) + Double.parseDouble(sData[i][4]))/4);
                        display.setText("The average of " + sName + " is: " + Double.toString(sAvrg) + "%." + "\n");
                        display.append(Arrays.deepToString(sData[i]) + "\n");
                        return;
                    } 
                    else {
                        assert true; 
                    }
                }
                JOptionPane.showMessageDialog(null, "Student does not exist!");
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Invalid input!");
        }
    }//GEN-LAST:event_btnSAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentGrades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCA;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSA;
    private javax.swing.JTextArea display;
    private javax.swing.JTextField inputFirstN;
    private javax.swing.JTextField inputLastN;
    private javax.swing.JTextField inputTest1;
    private javax.swing.JTextField inputTest2;
    private javax.swing.JTextField inputTest3;
    private javax.swing.JTextField inputTest4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFirstN;
    private javax.swing.JLabel lblLastN;
    private javax.swing.JLabel lblTest1;
    private javax.swing.JLabel lblTest2;
    private javax.swing.JLabel lblTest3;
    private javax.swing.JLabel lblTest4;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
