/**
 * ICS4UR Computer Science, 12 
 * Brampton, Canada
 *
 * https://github.com/HarisK03/
 * https://repl.it/@HarisKamal
 *
 * modified     20201013
 * date         20201012
 * @filename	Flight.java
 * @author      hkamal
 * @version     1.0
 * @see         StudentGrades program Assignment 2.7 - check points of flight passengers 
 */

import java.util.*;
import javax.swing.*;

// aeroplane img src: https://pngio.com/PNG/a114707-transparent-cartoon-airplane-png.html

public class Flight extends javax.swing.JFrame {

    /**
     * Creates new form Flight
     */
    public Flight() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblW1 = new javax.swing.JLabel();
        lblW2 = new javax.swing.JLabel();
        lblW3 = new javax.swing.JLabel();
        lblW4 = new javax.swing.JLabel();
        firstNIn = new javax.swing.JTextField();
        w2In = new javax.swing.JTextField();
        w3In = new javax.swing.JTextField();
        w4In = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();
        btnTP = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        display = new javax.swing.JTextArea();
        btnAdd = new javax.swing.JButton();
        lblFirstN = new javax.swing.JLabel();
        lblLastN = new javax.swing.JLabel();
        w1In = new javax.swing.JTextField();
        lastNIn = new javax.swing.JTextField();
        png1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Airline Points");

        lblW1.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        lblW1.setText("Week 1");

        lblW2.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        lblW2.setText("Week 2");

        lblW3.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        lblW3.setText("Week 3");

        lblW4.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        lblW4.setText("Week 4");

        firstNIn.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        w2In.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        w3In.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        w4In.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        btnExit.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnTP.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        btnTP.setText("Total Points");
        btnTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTPActionPerformed(evt);
            }
        });

        display.setEditable(false);
        display.setColumns(20);
        display.setRows(5);
        jScrollPane1.setViewportView(display);

        btnAdd.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        lblFirstN.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        lblFirstN.setText("First Name");

        lblLastN.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        lblLastN.setText("Last Name");

        w1In.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        lastNIn.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        png1.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        png1.setIcon(new javax.swing.ImageIcon("aeroplane.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblFirstN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(firstNIn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLastN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lastNIn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblW2)
                            .addComponent(lblW3)
                            .addComponent(lblW4)
                            .addComponent(lblW1))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(w3In, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(w4In, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(w2In, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(w1In, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(png1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(png1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLastN, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblFirstN)
                        .addComponent(firstNIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lastNIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblW1)
                    .addComponent(w1In, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblW2)
                    .addComponent(w2In, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblW3)
                    .addComponent(w3In, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblW4)
                    .addComponent(w4In, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTP)
                    .addComponent(btnExit)
                    .addComponent(btnAdd))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    List<List<String>> flight = new ArrayList<List<String>>(); 

    int a = 0;
   
    // method totals points for passenger
    private void btnTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTPActionPerformed
        try {
            String pName = firstNIn.getText() + " " + lastNIn.getText();
            int total = Integer.parseInt(w1In.getText()) + Integer.parseInt(w2In.getText()) + Integer.parseInt(w3In.getText()) + Integer.parseInt(w4In.getText());
            for (int i = 0; i < flight.size(); i++) {
                if (flight.get(i).get(0).equals(pName)) {
                    if (total < 5000) {
                        display.setText(pName + " has " + Integer.toString(total) + " points!\nUnfortunately they do not qualify for bonus points." + "\n" + flight.get(i).toString() + "\n");
                        return;
                    }
                    else {
                        display.setText(pName + " has " + Integer.toString(total) + " points!\nThey have qualified for 1000 bonus points!" + "\n" + flight.get(i).toString() + "\n");
                        return;
                    }
                }
            }
            JOptionPane.showMessageDialog(null, "Passenger does not exist!");
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "There are no passengers or invalid input (can't calculate total)!");
        }
    }//GEN-LAST:event_btnTPActionPerformed
   
    // method adds new passenger
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            if (firstNIn.getText().isEmpty() || lastNIn.getText().isEmpty() || w1In.getText().isEmpty() || w2In.getText().isEmpty() || w3In.getText().isEmpty() || w4In.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Missing field!");
                return;
            }
            
            String pName = (firstNIn.getText() + " " + lastNIn.getText());
            String w1 = (w1In.getText());
            String w2 = (w2In.getText());
            String w3 = (w3In.getText());
            String w4 = (w4In.getText());

            if (Integer.parseInt(w1In.getText()) < 0 || Integer.parseInt(w2In.getText()) < 0 || Integer.parseInt(w3In.getText()) < 0 || Integer.parseInt(w4In.getText()) < 0) {
                JOptionPane.showMessageDialog(null, "I don't think you can have negative points!");
                return;
            }

            else{
                flight.add(new ArrayList<String>());
                flight.get(a).add(pName);
                flight.get(a).add(w1);
                flight.get(a).add(w2);
                flight.get(a).add(w3);
                flight.get(a).add(w4);
                a++;
                display.setText("");
                for (int i = 0; i < a; i++) {
                    display.append(flight.get(i).toString() + "\n");
                }
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Invalid input!");
        }
    }//GEN-LAST:event_btnAddActionPerformed
    
    // method exit program
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Flight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Flight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Flight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Flight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Flight().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnTP;
    private javax.swing.JTextArea display;
    private javax.swing.JTextField firstNIn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastNIn;
    private javax.swing.JLabel lblFirstN;
    private javax.swing.JLabel lblLastN;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblW1;
    private javax.swing.JLabel lblW2;
    private javax.swing.JLabel lblW3;
    private javax.swing.JLabel lblW4;
    private javax.swing.JLabel png1;
    private javax.swing.JTextField w1In;
    private javax.swing.JTextField w2In;
    private javax.swing.JTextField w3In;
    private javax.swing.JTextField w4In;
    // End of variables declaration//GEN-END:variables
}
